language: node_js

node_js:
  - 11.6.0

cache:
  directories:
  - "node_modules"

notifications:
  email:
    on_success: never

branches:
  only:
    - master

before_install: git fetch --depth=1000

install:
  - npm i

script:
  - /bin/bash scripts/lint-commits.sh
  - npm run build
